apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
spec:
  selector:
    matchLabels:
      run: php-apache
  replicas: 6
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
      - name: php-apache
        image: k8s.gcr.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
      - name: php-apache-exporter
        image: bitnami/apache-exporter
        ports:
        - containerPort: 9117
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  labels:
    run: php-apache
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  selector:
    run: php-apache
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: apache-exporter
  labels:
    run: php-apache
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9117"
spec:
  ports:
    - port: 9117
  selector:
    run: php-apache
